[project]
name = "fastapi-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "djlint>=1.36.4",
    "fastapi[standard]>=0.129.0",
    "jinja2>=3.1.6",
]

[tool.djlint]
profile = "jinja"
